### ISSUE TITLE
[meta] improvements for scatter charts

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#528]
The point chart implementation is ready for substantial revision and additions.

First up:

- [ ] review the list of options available, and modernize it using the line chart options as a guide
- [x]  remove boilerplate, and integrate functions from line charts such as rollovers (relies on #534)
- [x] substantial code cleanup and test suite writing 
- [ ] figure out the best method for incorporating multiple data, a la multiple lines - there should be a few options
- [ ] clean up coloring and grouping options so the API is clear and consistent
- [ ] refine the least squares regression

Once these are done, we will target these new features:

- [ ] implement loess algorithm
- [ ] implement basic jittering (#538)

**Comment by brylie** [comment]
What would the API changes look like? Please add an example of the planned API to the description, for discussion and feedback.

**Comment by brylie** [comment]
Woah, I just found out about [Vega.js](http://vega.github.io/vega/) while researching LOESS implementations. Vega uses declarative semantics in almost every aspect of chart design. Lets look to Vega while considering the API design for charts such as the scatterplot.

**Comment by brylie** [comment]
On further inspection, some of the Vega declarative API may be a bit convoluted, compared with the elegance of declaring Metrics Graphics charts. However, it seems like Vega as a system has a well-thought-out organization, including interactivity and exporting:

> [Vega is] a declarative format for creating, saving, and sharing interactive visualization designs.

**Comment by hamilton** [comment]
I'm not sure what the API changes will look like. This is why the first point is "review the lists of options available".

**Comment by hamilton** [comment]
We are not going to be changing the API substantially. It will be very similar to what it is like for line charts. We just want to make sure that argument names and workflows are easy-to-use.
