### ISSUE TITLE
[META] Bar Charts - come up with a consistent, sensible design

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#580]
Bar charts are one of the big, important features our library doesn't support that I think folks really need. We have a half-hearted implementation of them. I personally wouldn't use it. So, one of the big goals for 2.9 is to have a sensible design & API for bar charts.

This issue will track the development from a meta-issue point of view. Bar charts will have:

- a sensible API for bar charts that is reflective of current practices
- the capacity for grouping in a cognitively-sound and opinionated way
- a clear design for categorical axes (really, a general need)

The working list of issues for this task:

- [x] #576 enable negative values on bar charts
- [x] #587 flesh out how chart heights get calculated, and how bar height factors in
- [x] #596 work through the data structures & API for bar charts
- [x] #598 work through the rollover functionality
