### ISSUE TITLE
META: bar type improvements / changes before removing 'experimental' tag

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#688]
The hope for 2.11 is to have bars and points relatively feature-complete and well-tested. This has been a gaping hole in the library since day one. Here are some remaining issues:

- [ ] rollovers for bar charts should mirror points and lines as much as possible
- [ ] legends for bar charts should not be plotted by default
- [ ] grouped bar charts need an option to not be colored by default
- [ ] ungrouped bar charts need an option to be colored
- [ ] we need to marry the ``histogram`` type to the ``bar`` type. A bar where one axis is numerical should appear like the current ``histogram`` type
- [ ] given the previous bullet, we need to make it so we can easily orient numerical-only bars either vertically or horizontally
- [ ] bar thickness needs to be something we can easily set
- [ ] we need to re-implement the other bullet-like parts of bars, including middle lines, goal ticks, and the like
- [ ] we need to have a way to support sub-label accessing (a secondary label underneath a categorical one which can provide more information)
