### ISSUE TITLE
META: point chart improvements / tweaks

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#689]
This is a meta-issue for point charts for 2.11. For the most part there isn't too much more to do with points to get it to be feature complete. Here are the remaining ones:

- [ ] create a consistent coloring schema for points
- [ ] work with groups of arrays for points, color-wise, the way we work with groups of arrays for lines
- [ ] thoroughly test current least squares implementation to make sure it works as expected
- [ ] thoroughly test my rough loess implementation until it is stable
- [ ] have it so that both least squares and loess can be implemented on groups of points, for multiple lines on one graph
- [ ] provide error bands around both LS and loess
