### ISSUE TITLE
[META] We'd like to modernize the MG codebase.

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#807]
Our high-level aim over the next few months is to get Metrics Graphics into a more modern state. This codebase was developed in another era, and in a ES-averse manner.

The library _works_ as we'd expect. In theory, the code is reasonably clear enough to read and contribute to, if you're comfortable with the idiosyncratic and outdated style of the JS we used when we were last contributing full-steam. But the second-order effect is that it's much more difficult to add new features, test, and have fruitful contributions from others because no one writes JS this way anymore, and that hurts MG.

This issue will reflect discussion & the high-level steps needed to make this happen.

- [ ] remove stale dependencies (particularly all references to bootstrap and jquery)
- [ ] clarify the data-to-graphic pipeline and make it much clearer
- [ ] update the general code to reflect modern ECMAScript standards, suitably decomposed for better testing
- [ ] update the build system to reflect modern practices

We will be tackling these refactors in a series of PRs over the coming months.

**Comment by lobax** [comment]
Hi, 

We are four master students taking a course in software engineering, and as part of our coursework we are tasked with refactoring code in a large, active open source project and provide roughly 30 hours of work per person (this includes the time it takes to get up to speed with the project). 

Since you are in the process of refactoring your codebase, we would like to offer our help! Is there any specific subtask that would be a good candidate?

**Comment by wlach** [comment]
@lobax that's pretty interesting, I think the most accessible task will likely be modernizing the code to modern ecmascript standards, we probably want to enable babel transpilation (#809) before allowing that to proceed. @hamilton what do you think?

**Comment by lobax** [comment]
@wlach Great! Since we have a deadline for this, we will proceed on a fork. 

Is there some specific part of the codebase that you feel we should start with?

**Comment by hamilton** [comment]
@wlach I think this sounds like exactly the right first step! Having babel transpilation will make it much easier to migrate the code base piece-by-piece.

**Comment by wlach** [comment]
@lobax I created a new issue #811 to track the ES6 stuff in particular. If possible, I would try to use some kind of tool to run these sorts of transformations in batches. If you finish early, there are certainly some other things we could have you do. :)

**Comment by garygreen** [comment]
Does anyone know of a different library that is more modern than Metric Graphics? It looks like this library is lagging behind a bit so wondering if it's worth just calling it a day and finding an alternative... anyone have any recommendations? 😃

**Comment by wlach** [comment]
> Does anyone know of a different library that is more modern than Metric Graphics? It looks like this library is lagging behind a bit so wondering if it's worth just calling it a day and finding an alternative... anyone have any recommendations? 😃

Realistically this may be the best option for you, though I have not yet found something which hits all the sweet spots MG does yet. Some popular charting libraries used by others @ Mozilla include:

* chart.js: https://www.chartjs.org/
* plotly.js: https://plot.ly/javascript/
